-----C18
SELECT COUNT(DEAN.MaDA) as 'Tổng đề án'
	FROM DEAN
-----C19
SELECT TenPhg, TenDA
FROM NHANVIEN INNER JOIN PHONGBAN ON NHANVIEN.Phong = PHONGBAN.MaPhg INNER JOIN PHANCONG ON NHANVIEN.MaNV = PHANCONG.MaNV
INNER JOIN DEAN ON DEAN.MaDA = PHANCONG.MaDA
GROUP BY TenPhg, TenDA
-----C20
select TenPhg,count(*) as' Số lượng'
	from PHONGBAN,DEAN
	where MaPhg=TenPhg
	group by TenPhg
-----C21
SELECT COUNT(DEAN.MaDA) as 'Số lượng đề án'
	FROM DEAN, PHONGBAN
	WHERE DEAN.MaDA = PHONGBAN.MaPhg AND
		  PHONGBAN.TenPhg = N'Nghiên cứu'
-----C22
SELECT AVG(NHANVIEN.Luong) as'Lương trung bình'
	FROM NHANVIEN
	WHERE NHANVIEN.Phai = N'Nữ'
-----C23
SELECT COUNT(THANNHAN.MaNV) as' Nhân thân'
	FROM NHANVIEN, THANNHAN
	WHERE NHANVIEN.MaNV = THANNHAN.MaNV AND
		  NHANVIEN.HoNV = N'Đinh' AND
		  NHANVIEN.TenLot = N'Bá' AND
		  NHANVIEN.TenNV = N'Tiến'
-----C24
SELECT (HoNV  + ' ' + TenLot + ' ' + TenNV) AS N'Họ Tên', YEAR(NgSinh) AS N'Năm sinh'
FROM NHANVIEN
ORDER BY (2023-YEAR(NgSinh)) ASC
-----C25
SELECT DEAN.MaDA, SUM(PHANCONG.ThoiGian) as'Tổng số giờ'
	FROM DEAN, PHANCONG
	WHERE DEAN.MaDA = PHANCONG.MaDA
	GROUP BY DEAN.MaDA
-----C26
SELECT DEAN.TenDA, SUM(PHANCONG.ThoiGian) as'Tổng số giờ'
	FROM DEAN, PHANCONG
	WHERE DEAN.MaDA = PHANCONG.MADA
	GROUP BY  DEAN.TenDA
-----C27
select TenDA+'' as 'Tên đề án' ,count(*) as 'số lượng nhân viên'
	from NHANVIEN,DEAN
	where TenDA= DEAN.TenDA
	group by DEAN.TenDA
-----C28
SELECT (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV) AS 'Họ tên nhân viên', COUNT(THANNHAN.MaNV) AS 'Số lượng thân nhân'
	FROM NHANVIEN, THANNHAN
	WHERE NHANVIEN.MaNV = THANNHAN.MaNV
	GROUP BY (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV)
-----C29
SELECT (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV) AS 'Họ tên nhân viên', COUNT(PHANCONG.MaNV) AS'Số lượng đề án tham gia'
	FROM NHANVIEN, DEAN, PHANCONG
	WHERE NHANVIEN.MaNV = PHANCONG.MaNV AND
		  DEAN.MaDA = PHANCONG.MaDA
	GROUP BY (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV)
------C30
SELECT PHONGBAN.MaPhg, PHONGBAN.TenPhg, AVG(NHANVIEN.Luong) AS 'Lương trung bình'
	FROM NHANVIEN, PHONGBAN
	WHERE NHANVIEN.Phong = PHONGBAN.MaPhg
	GROUP BY PHONGBAN.MaPhg, PHONGBAN.TenPhg
-----C31
	SELECT PHONGBAN.TenPhg, COUNT(NHANVIEN.MaNV) AS N'Số lượng nhân viên'
	FROM NHANVIEN, PHONGBAN
	WHERE NHANVIEN.Phong = PHONGBAN.MaPhg
	GROUP BY PHONGBAN.TenPhg
	HAVING AVG(NHANVIEN.Luong)>5200000
-----C32
select TENPHG,count(DEAN.TenDA) as 'Số lượng đề án'
	from PHONGBAN,DEAN
	where MaPhg= MaDA
	group by TENPHG
-----C33
SELECT PHONGBAN.TENPHG, (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV) AS 'Họ tên trưởng phòng', COUNT(DEAN.DDiemDA) AS 'Số lượng đề án'
	FROM NHANVIEN, PHONGBAN, DEAN
	WHERE NHANVIEN.MaNV = PHONGBAN.TenPhg AND
		  PHONGBAN.MaPhg = DEAN.DDiemDA
	GROUP BY PHONGBAN.TenPhg, (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV)
-----C34
SELECT (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV) AS 'Họ tên nhân viên', COUNT(PHANCONG.MaNV) AS'Số lượng đề án tham gia'
	FROM NHANVIEN, DEAN, PHANCONG
	WHERE NHANVIEN.MaNV = PHANCONG.MaNV AND
		  DEAN.MaDA = PHANCONG.MaDA
	GROUP BY (NHANVIEN.HoNV + ' ' + NHANVIEN.TenLot + ' ' + NHANVIEN.TenNV)